version: '3.8'

services:
  # Основное приложение (FastAPI + Streamlit)
  rag-app:
    build: .
    container_name: rag-pdf-app
    ports:
      - "8000:8000"  # FastAPI
      - "8503:8503"  # Streamlit
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=rag_db
      - POSTGRES_USER=rag_user
      - POSTGRES_PASSWORD=rag_password
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_USER=admin
      - OPENSEARCH_PASSWORD=admin
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=rag-documents
      - MINIO_SECURE=false
      - YANDEX_API_KEY=${YANDEX_API_KEY}
      - YANDEX_FOLDER_ID=${YANDEX_FOLDER_ID}
      - YANDEX_LLM_MODEL=yandexgpt-lite
      - YANDEX_EMBEDDING_MODEL=text-search-doc
      - VECTOR_DIMENSION=256
    depends_on:
      - postgres
      - opensearch
      - minio
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - rag-network

  # PostgreSQL база данных
  postgres:
    image: postgres:15
    container_name: rag-postgres
    environment:
      - POSTGRES_DB=rag_db
      - POSTGRES_USER=rag_user
      - POSTGRES_PASSWORD=rag_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    networks:
      - rag-network

  # OpenSearch для поиска и векторных операций
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: rag-opensearch
    environment:
      - cluster.name=rag-cluster
      - node.name=rag-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    restart: unless-stopped
    networks:
      - rag-network

  # OpenSearch Dashboards (опционально)
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: rag-opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - opensearch
    restart: unless-stopped
    networks:
      - rag-network

  # MinIO для хранения файлов и изображений
  minio:
    image: minio/minio:latest
    container_name: rag-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - rag-network

  # MinIO Client для создания bucket
  minio-init:
    image: minio/mc:latest
    container_name: rag-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set ragminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb ragminio/rag-documents --ignore-existing;
      /usr/bin/mc policy set public ragminio/rag-documents;
      exit 0;
      "
    networks:
      - rag-network

# Volumes для постоянного хранения данных
volumes:
  postgres_data:
    driver: local
  opensearch_data:
    driver: local
  minio_data:
    driver: local

# Сеть для связи между контейнерами
networks:
  rag-network:
    driver: bridge 